import "./globals.css";

import localFont from "next/font/local";
const myFont = localFont({
  src: [
    {
      path: "../public/fonts/GS-Regular.woff",
      weight: "400",
    },
    {
      path: "../public/fonts/GS-Medium.woff",
      weight: "500",
    },
    {
      path: "../public/fonts/GS-Bold.woff",
      weight: "700",
    },
  ],
  variable: "--font-myfont",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${myFont.variable} appFont`}>
      <body>{children}</body>
    </html>
  );
}
